name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload arm64 artifacts
      id: upload-arm64-apk
      uses: actions/upload-artifact@v3
      with:
        name: release-arm64-apk
        path: app/build/outputs/apk/app/release/*arm64-v8a.apk
      continue-on-error: true

    - name: Upload armv7 artifacts
      id: upload-armv7-apk
      uses: actions/upload-artifact@v3
      with:
        name: release-armv7-apk
        path: app/build/outputs/apk/app/release/*-v7a.apk
      continue-on-error: true

    - name: Upload universl artifacts
      id: upload-universal-apk
      uses: actions/upload-artifact@v3
      with:
        name: release-universal-apk
        path: app/build/outputs/apk/app/release/*universal.apk
      continue-on-error: true
